# Generated by Django 2.0.2 on 2018-03-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180331_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='first_name',
        ),
    ]
