# Generated by Django 2.0.2 on 2018-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_employees_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
    ]
