# Generated by Django 2.0.2 on 2018-03-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180331_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='emp_slug',
            new_name='slug',
        ),
    ]
